name: FoundryDocGen

on:
  release:
    types: [published]

env:
  FOUNDRY_PROFILE: ci

jobs:
  readmeDocGen:
    strategy:
      fail-fast: true

    name: Foundry Doc Gen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge Doc
        run: ./script/docs/docgen.sh
        id: docgen
        timeout-minutes: 5

      - name: Sync Markdown to ReadMe
        uses: readmeio/rdme@7.2.0
        with:
         rdme: docs ./forgedocs2 --version=v1.0 --key=${{ secrets.README_KEY }}
